[project]
name = "rag-math-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "latex2sympy2>=1.9.1",
    "pylatexenc>=2.10",
    "pymupdf>=1.25.5",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
    "sentence-transformers>=4.1.0",
    "sympy>=1.14.0",
    "weaviate-client==3.26.2",
]
